### ISSUE TITLE
Character data test - character sets

### ISSUE THREAD

**Issue by imanuelcostigan** [rstats-db/DBItest#77]
One of the parts of the `data_character()` tests is executing the following query: `SELECT 'Кирилл' AS A`. 

By default, this will return `?????` in SQL Server (even natively). What needs to be executed is `SELECT N'Кирилл' AS A`. This is because, by default, SQL Server uses a non-UNICODE character set so one needs to declare a string literal as UNICODE using the `N'` prefix. 

As a result this test case fails.

**Comment by krlmlr** [comment]
Is the N prefix part of the standard, or a SQL server extension? Anyway, we might need a tweak here.

**Comment by imanuelcostigan** [comment]
i suspect the latter. A quick search suggests that maybe Oracle has a similar "feature"

**Comment by krlmlr** [comment]
From [T-SQL docs](https://msdn.microsoft.com/en-us/library/ms179899.aspx):

> Unicode strings have a format similar to character strings but are preceded by an N identifier (N stands for National Language in the SQL-92 standard). MySQL and PostgreSQL accept this syntax (I'm not sure about the semantics), SQLite rejects it.

MySQL has "introducers", too, looks like you can ask `SELECT _utf8'text'`. However, things work out without these introducers here because the connection character set is changed to utf8 first thing after establishing the connection. I suspect this isn't possible with jTDS (see somewhat related [SO question](http://stackoverflow.com/q/1322421/946850)), but I might be wrong.
